CrossMedia/Controllers/Admin/AdminAreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrossMedia.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminAreaController : Controller
    {
        // GET: AdminArea
        public ActionResult Index()
        {
            return View();
        }

        //public ActionResult Users()
        //{
        //    r
        //}
    }
}

CrossMedia/Controllers/BudgetController.cs
using CrossMedia.Models;
using CrossMedia.Models.Database;
using CrossMedia.Models.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrossMedia.Controllers
{
    [Authorize]
    public class BudgetController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var model = new BudgetViewModel();
            var currentLoggedInUser = User.Identity.GetUserId();

            // Al deze linq queries worden nog niet uitgevoerd..
            // Pas in de "index.cshtml" worden ze uitgevoerd.
            //alle items van de ingelogde gebruiker ophalen

            //groupeer op Category, bijv: als een item er meerdere keren in voorkomt dat deze opgeteld word
            //en verdeeld worden per categorie
            var result = from item in db.ItemsPerUser
                where item.UserID.Equals(currentLoggedInUser)
                group item by item.Item.CategoryID
                into groep
                select new TotalOrderItems
                {
                    ItemId = groep.Key,
                    Totaal = groep.Sum(x => x.Quantity.Value * x.Item.Price)
                };
            model.TotalOrderCosts = result.ToArray();

            ViewBag.Expenses = result;

            //De budgets per categorie van de gebruiker 
            var budgets =
                db.Budgets.Where(b =>
                    b.UserID.Equals(currentLoggedInUser, StringComparison.InvariantCultureIgnoreCase));

            model.Budgets = budgets.ToArray();

            // je moet nu je model vullen met de informatie die je nog hebt op je pagina.
            // En je html pagina maken van het type BudgetViewModel  , Alles zit in BudgetViewModel toch wat ik gebruik
            return View(model);
        }
    }
}

CrossMedia/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrossMedia.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CrossMedia/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CrossMedia/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CrossMedia/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@Styles.Render("~/Content/css/style.css",
    "~/Content/css/slick.css",
    "~/Content/css/slick-theme.css",
    "~/Content/css/no-js.css",
    "~/Content/css/jquery.fancybox.css",
    "~/Content/css/font-awesome.min.css"
 )


    <div id="preloader">
        <div class="spinner"></div> <!-- page loader spinner -->
    </div>

    <!-- #features -->
    <div id="features" class="row-section" style="margin-top:10%; margin-bottom:20%;">

        <!-- .container -->
        <div class="container">

            <!-- .row -->
            <div class="row">

                <div class="col-sm-3 ">
                    <!-- 1 -->
                    <a href="@Url.Action("Index", "Budget")">
                        <div class="affa_feature_icon_top">
                            <i class="fa fa-euro"></i>
                            <h4>Budget</h4>
                            <p></p>
                        </div>
                    </a>
                </div>

                <div class="col-sm-3 ">
                    <!-- 2 -->

                    <a href="views/expense.html">
                        <div class="affa_feature_icon_top">
                            <i class="fa fa-cart-plus"></i>
                            <h4>Expenses</h4>
                            <p></p>
                        </div>
                    </a>
                </div>


                <div class="col-sm-3 " >
                    <!-- 3 -->
                    <a href="#">
                        <div class="affa_feature_icon_top">
                            <i class="fa fa-bar-chart"></i>
                            <h4>Statistics</h4>
                            <p></p>
                        </div>
                    </a>
                </div>

                <div class="col-sm-3 ">
                    <!-- 3 -->
                    <a href="#">
                        <div class="affa_feature_icon_top">
                            <i class="fa fa-list-alt"></i>
                            <h4>Survey</h4>
                            <p></p>
                        </div>
                    </a>
                </div>
                @if (System.Web.HttpContext.Current.User.IsInRole("admin"))
                {
                    <div class="col-sm-3 ">
                        <!-- 3 -->
                        <a href="@Url.Action("Index", "AdminArea")">
                            <div class="affa_feature_icon_top">
                                <i class="fa fa-user"></i>
                                <h4>Admin Area</h4>
                                <p></p>
                            </div>
                        </a>
                    </div>
                }
            </div>
            <!-- .row end -->

        </div>
        <!-- .container end -->

    </div>
    <!-- #features end -->
    <!-- #bottom -->
    <div id="bottom">

        <!-- .container -->
        <div class="container">

            <div class="post-heading-center">
                <h2>Download Budgetify now</h2>
                <p></p>
            </div>

            <div class="bottom-button">
                <a href="#" class="btn-custom btn-icon">
                    <i class="fa fa-android"></i> <em>Not available on</em>Google
                    Play
                </a>
                <a href="#" class="btn-custom btn-icon"><i class="fa fa-apple"></i> <em>Not available on</em>App Store</a>
            </div>

            <div class="sep-border"></div> <!-- separator -->

            <div class="subscribe-form">
                <div class="post-heading-center2">
                    <p></p>
                    <h2>Subscribe to our newsletter!</h2>
                </div>

                <form method="post" action="#" class="affa-form-subscribe">
                    <input type="text" name="email" placeholder="Enter your e-mail address...." />
                    <input type="submit" name="submit" value="">
                </form>
            </div>

            <!--<div class="social-links">-->
            <!--<a href="#" title="facebook"><i class="fa fa-facebook"></i></a>-->
            <!--<a href="#" title="twitter"><i class="fa fa-twitter"></i></a>-->
            <!--<a href="#" title="google plus"><i class="fa fa-google-plus"></i></a>-->
            <!--<a href="#" title="instagram"><i class="fa fa-instagram"></i></a>-->
            <!--<a href="#" title="pinterest"><i class="fa fa-pinterest"></i></a>-->
            <!--<a href="#" title="dribbble"><i class="fa fa-dribbble"></i></a>-->
            <!--</div>-->

            <footer class="footer-text">
                <p>Powered by <b>Cunts</b></p>
            </footer>

        </div>
        <!-- .container end -->

    </div>